### ISSUE TITLE
[讨论]请教如何部署？

### ISSUE THREAD

**Issue by kevin7lou** [miRoox/wiki#2]
你好！请教一下：

- 如何部署在github page上的？我看其他人在仓库里都有一个index.html的文件，你的没有？
- 另外，如何实现 `xxx.github.io/wiki/` 的部署？在阿里云买了二级域名？

谢谢啦！

**Comment by miRoox** [comment]
你好

其实就是通过Travis CI<https://travis-ci.org/> 部署到gh-pages分支，然后由Github Pages部署到实际的网页上。所以index.html在gh-pages分支上。至于子域名，除去本身名为xxx.github.io的仓库，其它仓库默认就是部署在对应的子域名下的。

至于自动部署的具体过程，我主要是参考的Blog自动部署实践: Hugo + Travis CI -> GitHub Pages<https://blog.yuantops.com/tech/hugo-travis-ci-auto-deploy-to-gh-pages/> 只是hugo换成了npm。你也可以看看我的仓库<https://github.com/miRoox/wiki>是怎么配的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kevin Lou<mailto:notifications@github.com>
发送时间: 2020年4月26日 16:12
收件人: miRoox/wiki<mailto:wiki@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [miRoox/wiki] [讨论]请教如何部署？ (#2)


你好！请教一下：

  *   如何部署在github page上的？我看其他人在仓库里都有一个index.html的文件，你的没有？
  *   另外，如何实现xxx.github.io/wiki/ 的部署？在阿里云买了二级域名？

谢谢啦！

―

**Comment by miRoox** [comment]
其实就是通过 [Travis CI](https://travis-ci.org) 部署到gh-pages分支，然后由Github Pages部署到实际的网页上。所以index.html在gh-pages分支上。至于子域名，除去本身名为xxx.github.io的仓库，其它仓库默认就是部署在对应的子域名下的。

至于自动部署的具体过程，我主要是参考的[Blog自动部署实践: Hugo + Travis CI -> GitHub Pages](https://blog.yuantops.com/tech/hugo-travis-ci-auto-deploy-to-gh-pages) 只是hugo换成了npm。你也可以看看我的仓库是怎么配的。
